/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.3
 * Generated at: 2015-11-12 10:49:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/maps.jsp", Long.valueOf(1447228398268L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Main Page ..</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/csssheet.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/core.css\">\r\n");
      out.write("<script src=\"css/core.js\"></script>\r\n");
      out.write("<link href=\"jQueryAssets/jquery.ui.core.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"jQueryAssets/jquery.ui.theme.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"jQueryAssets/jquery.ui.dialog.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"jQueryAssets/jquery.ui.resizable.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script src=\"jQueryAssets/jquery-1.8.3.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"jQueryAssets/jquery-ui-1.9.2.dialog.custom.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/userlogin.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/core.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/fblogin.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <header>\r\n");
      out.write("  <a href=\"#\"><img src=\"css/header1.jpg\" width=\"962\" height=\"175\"  alt=\"\"/></a></header>\r\n");
      out.write("  <div class=\"sidebar1\">\r\n");
      out.write("  <nav>\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li><a href=\"#\" id=\"signup\"  style=\"text-decoration: none;\">Apply Now</a>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"index.jsp\" id=\"ulogin\"  style=\"text-decoration: none;\">Login</a></li>\r\n");
      out.write("          <li><a href=\"#\" style=\"text-decoration: none;\">About us</a></li>\r\n");
      out.write("          \r\n");
      out.write("          <li><a href=\"#\" style=\"text-decoration: none;\">Help</a></li>\r\n");
      out.write("          \r\n");
      out.write("          <li><a style=\"text-decoration: none;\" href=\"#\">Contact us</a></li>\r\n");
      out.write("          <li><a style=\"text-decoration: none;\" href=\"#\" id=\"map1\">Map</a></li>\r\n");
      out.write("        \t<li></li>\r\n");
      out.write("        \t<li></li><li></li><li></li><li></li>             \r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </nav>\r\n");
      out.write("    <aside>\r\n");
      out.write("      <p></p>\r\n");
      out.write("      <p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p></p>\r\n");
      out.write("    </aside>\r\n");
      out.write("  <!-- end .sidebar1 --></div>\r\n");
      out.write("  <article class=\"content\">\r\n");
      out.write("    <h1>Welcome To HR management System</h1>\r\n");
      out.write("    <section>\r\n");
      out.write("        <h2><iframe height=\"400px\" width=\"100%\" name=\"frame1\" src=\"css/hr.gif\"></iframe>&nbsp;</h2>\r\n");
      out.write("    </section>\r\n");
      out.write("  <!-- end .content --></article>\r\n");
      out.write("    <aside style=\" height: 400px\">\r\n");
      out.write("    <h4>Latest News</h4><hr>\r\n");
      out.write("    <marquee  behavior=\"scroll\" direction=\"up\"  onMouseOver=\"stop();\" onMouseOut=\"start()\">\r\n");
      out.write("        <font style=\" color:  tomato\"> <p><a href=\"#\"><s:property value=\"applicationid\"/></a></p>\r\n");
      out.write("    <p><a href=\"#\" style=\" text-decoration:  none\">News1</a></p>\r\n");
      out.write("    <p><a href=\"#\"  style=\" text-decoration:  none\">News1</a></p>\r\n");
      out.write("    <p><a href=\"#\"  style=\" text-decoration:  none\">News1</a></p>\r\n");
      out.write("    <p><a href=\"#\" style=\" text-decoration:  none\">News1</a></p>\r\n");
      out.write("     <p><a href=\"#\"  style=\" text-decoration:  none\">News1</a></p>\r\n");
      out.write("    <p><a href=\"#\"  style=\" text-decoration:  none\">News1</a></p>\r\n");
      out.write("    <p><a href=\"#\"  style=\" text-decoration:  none\">News1</a></p>\r\n");
      out.write("    <p><a href=\"#\"  style=\" text-decoration:  none\">News1</a></p>\r\n");
      out.write("    <p><a href=\"#\"  style=\" text-decoration:  none\">news1</a></p></font>\r\n");
      out.write("    </marquee>\r\n");
      out.write("  </aside>\r\n");
      out.write("    <footer align=\"center\">\r\n");
      out.write("               Chandrakesh Shukla(Kiit University)\r\n");
      out.write("    </footer>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"feedback\">\r\n");
      out.write("\t<a id=\"feedback_button\">Feedback</a>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"form\">\r\n");
      out.write("\t<h2>Please Send Us Your Feedback</h2>\r\n");
      out.write("\t\t<span class=\"status\"></span>\r\n");
      out.write("\t\t<textarea id=\"feedback_text\"></textarea>\r\n");
      out.write("\t\t<input type=\"button\" value=\"Send\" id=\"submit_form\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("        <div id=\"map2\" style=\" height:100 \" hidden=\"true\">\r\n");
      out.write("        ");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("  <head>\n");
      out.write("    <style>\n");
      out.write("      html, body, #map-canvas {\n");
      out.write("        height: 100%;\n");
      out.write("        margin: 0px;\n");
      out.write("        padding: 0px\n");
      out.write("      }\n");
      out.write("    </style>\n");
      out.write("    <script src=\"https://maps.googleapis.com/maps/api/js?v=3.exp\"></script>\n");
      out.write("    <script>\n");
      out.write("function initialize() {\n");
      out.write("  var myLatlng = new google.maps.LatLng(20.358227,85.812235);\n");
      out.write("  var mapOptions = {\n");
      out.write("    zoom: 16,\n");
      out.write("    center: myLatlng\n");
      out.write("  };\n");
      out.write("\n");
      out.write("  var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);\n");
      out.write("\n");
      out.write("  var contentString = '<div id=\"content\">'+\n");
      out.write("      '<div id=\" Chandrakesh Shukla(KIIT UNIVERSITY)\">'+\n");
      out.write("      '</div>'+\n");
      out.write("      '<h3 id=\"KIIT\" class=\"KIIT\">KIIT UNIVERSITY</h3>'+\n");
      out.write("      '<div id=\"bodyContent\">'+\n");
      out.write("      ' <a href=\"www.Kiit.ac.in\"></a> '+\n");
      out.write("      '</p>'+\n");
      out.write("      '</div>'+\n");
      out.write("      '</div>';\n");
      out.write("\n");
      out.write("  var infowindow = new google.maps.InfoWindow({\n");
      out.write("      content: contentString\n");
      out.write("  });\n");
      out.write("\n");
      out.write("  var marker = new google.maps.Marker({\n");
      out.write("      position: myLatlng,\n");
      out.write("      map: map,\n");
      out.write("      title: 'Chandrakesh Shukla (KIIT UNIVERSITY)'\n");
      out.write("  });\n");
      out.write("  google.maps.event.addListener(marker, 'click', function() {\n");
      out.write("    infowindow.open(map,marker);\n");
      out.write("  });\n");
      out.write("}\n");
      out.write("\n");
      out.write("google.maps.event.addDomListener(window, 'load', initialize);\n");
      out.write("\n");
      out.write("    </script>\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("      <div id=\"map-canvas\" style=\" height: 600px\"></div>\n");
      out.write("  </body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
